M48
; DRILL file {KiCad 9.0.6} date 2026-05-11T14:07:19+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-11T14:07:19+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
%
G90
G05
T1
X152.4Y-77.0
T2
X134.6Y-97.4
X134.6Y-103.18
M30
